Update dark-sites.config
darkreader/darkreader pull request #10229
Opened 2022-11-02 18:38 UTC by 0PandaDEV

please add these they support dark mode and with dark reader its messed up

2022-11-07 13:10 UTC, Gusted requested changes

2022-11-07 13:10 UTC, Gusted commented on src/config/dark-sites.config
> +pandadev.tk
Please order the sites in the list.

2022-11-08 10:26 UTC, 0PandaDEV commented on src/config/dark-sites.config
> +pandadev.tk
What do you mean?

2022-11-08 10:32 UTC, 0PandaDEV commented on src/config/dark-sites.config
> +pandadev.tk
i updated it

2022-11-09 17:43 UTC, 0PandaDEV commented on src/config/dark-sites.config
> +waradu.tk
actually what means WIP?

2022-11-09 19:03 UTC, Gusted approved these changes
LGTM. Thanks!

2022-11-09 19:12 UTC, merged