Update dark-sites.config
darkreader/darkreader pull request #10459
Opened 2022-12-11 05:28 UTC by JustDesoroxxx

For some reasons dark reader extension glitches with my website and anyway my website follows user them so adding it here won't hurt

2022-12-14 13:37 UTC, Gusted requested changes

2022-12-14 13:37 UTC, Gusted commented on src/config/dark-sites.config
> +justdesoroxxx.github.io/Portfolio/
Please add it in alphabetic order.

2022-12-20 08:30 UTC, JustDesoroxxx commented
Normally it should be good now

2023-01-02 18:43 UTC, Gusted approved these changes

2023-01-02 18:43 UTC, merged