Fix for mapy.cz
darkreader/darkreader pull request #12209
Opened 2024-01-26 09:46 UTC by Tinh1000000

Invert map tiles used on 2D maps
Fix map markers with improper appearances while planning directions (.icon polygon & CSS)

2024-01-26 11:51 UTC, Tinh1000000 commented
For landscan.ornl.gov:

Invert OSM tiles used for map
Adjust population density legend to use original key colours (manually specifying them individually for now, I do not immediately know of a way to specifically ignore changes to the legend)

2024-01-27 21:57 UTC, Myshor requested changes
I reject for the part of landscan.ornl.gov

2024-01-27 21:57 UTC, Myshor commented on src/config/dynamic-theme-fixes.config
> +landscan.ornl.gov
As for maps.cz it seems it works nice but for this map is not.

Have you zoomed map to some city when default landscan is enabled?
Without your fix it's like this:
![obraz](https://github.com/darkreader/darkreader/assets/56877029/31753d71-f684-4f33-8b59-470ca6aadb8e)

but after updates it is more eye-painfull:
![obraz](https://github.com/darkreader/darkreader/assets/56877029/2a1676d8-507c-4dad-8654-b281fdd0a1a6)

Not sure if I would like to touch this map at all.

2024-01-28 17:37 UTC, Myshor approved these changes

2024-01-28 17:38 UTC, Myshor commented
Now it looks darker... Merging. 😉

2024-01-28 18:00 UTC, merged