Fix code cells on chat.openai.com
darkreader/darkreader pull request #12432
Opened 2024-03-09 04:53 UTC by alexalekseyenko

The code blocks on [chat.openai.com](chat.openai.com) are already dark and prior to this change Filter/Filter+ mode would invert them.

Before:
![Screenshot 2024-03-08 at 20 49 05](https://github.com/darkreader/darkreader/assets/17463710/39bc30a4-95b9-4baf-bf21-991ee45c2fc9)

After:
![Screenshot 2024-03-08 at 20 48 55](https://github.com/darkreader/darkreader/assets/17463710/daa7a8e5-da6c-4af8-a02e-3b52f2163e88)

2024-03-10 17:33 UTC, Myshor requested changes

2024-03-10 17:33 UTC, Myshor commented on src/config/inversion-fixes.config
> +pre .dark
Why to INVERT something that is good.
Check how NO INVERT section looks like in this file and apply that here.

I could do that by myself but if you will make that change you will learn something new. 😉

2024-03-13 21:12 UTC, alexalekseyenko commented
When the rule is in `INVERT` I get this:
<img width="749" alt="Screenshot 2024-03-13 at 14 10 25" src="https://github.com/darkreader/darkreader/assets/17463710/99cff278-0cec-4f7a-a03e-e1e7f2f19490">

but when it's in `NO INVERT` I get this:
<img width="774" alt="Screenshot 2024-03-13 at 14 10 59" src="https://github.com/darkreader/darkreader/assets/17463710/9fc166f1-3acc-4d91-8b14-db0412163d0f">

I haven't looked into the dark reader source in a while so apologies if I'm misunderstanding how this is supposed to work

2024-03-14 06:06 UTC, Myshor approved these changes

2024-03-14 06:06 UTC, Myshor commented
OK thanks for the screens.

Merging.

2024-03-14 06:06 UTC, merged