Update dynamic-theme-fixes.config
darkreader/darkreader pull request #12667
Opened 2024-05-02 21:27 UTC by L11K

SVG icons were turning dark instead of remaining white, for better visibility, for both light and dark themes.

As seen here: 
![image](https://github.com/darkreader/darkreader/assets/18279534/1a96870b-9648-4142-bb60-f81cfdc09b7e)                             ![image](https://github.com/darkreader/darkreader/assets/18279534/50de6563-d14a-444d-9eb8-2811968f728c)

2024-05-03 17:40 UTC, alexanderby commented
Hi @L11K, did it look fine before? Or did you notice the problem recently?

2024-05-03 18:31 UTC, alexanderby commented
If you look at these SVG icons in Chrome (or FireFox) Dev Tools, do you see `role="img"` attribute?

2024-05-03 18:33 UTC, L11K commented
> Hi @L11K, did it look fine before? Or did you notice the problem recently?

It always looked like this, but I was too lazy to "fix" it before yesterday. Now I want my coworkers to use the extension too, which having to apply the "fix" to them one-by-one, as they aren't as techno-able.
![image](https://github.com/darkreader/darkreader/assets/18279534/aba306df-f590-4fdf-92b4-ea03eaa58099)

2024-05-03 18:37 UTC, L11K commented
> If you look at these SVG icons in Chrome (or FireFox) Dev Tools, do you see `role="img"` attribute?

Not that I noticed, no
![image](https://github.com/darkreader/darkreader/assets/18279534/909f4008-6c8b-4672-a749-cd1d2b1b4965)

2024-05-03 18:42 UTC, alexanderby commented
I meant the `<svg role="img">`. I see it's there. Thanks for reporting, I will revert my change that causes the issue.

2024-05-03 18:46 UTC, L11K commented
> I meant the `<svg role="img">`. I see it's there. Thanks for reporting, I will revert my change that causes the issue.

Ah, yes, after data-icon. Thankfully even tho I didn't see, I posted the screenshot. 

Thanks for your time and patience.

2024-05-04 14:26 UTC, Myshor requested changes
Not starting tests until commit will be fixed.

2024-05-04 14:26 UTC, Myshor commented on src/config/dynamic-theme-fixes.config
> +================================
Keep the style of fixes - one empty line before that one should be added.

2024-05-04 14:26 UTC, Myshor commented on src/config/dynamic-theme-fixes.config
>  ================================
Same missing empty line here.

2024-05-04 15:44 UTC, Myshor approved these changes

2024-05-04 15:52 UTC, Myshor commented
@alexanderby after reading your comments I think I will leave it to you if it should be merged or not.

2026-05-06 19:31 UTC, Myshor commented
Untouched in 2 years. Closing.

2026-05-06 19:31 UTC, closed without merging