Fix (unified) transaction listing on PayPal.com
darkreader/darkreader pull request #12689
Opened 2024-05-07 08:29 UTC by oberrich

Before:
![image](https://github.com/darkreader/darkreader/assets/6305520/98ceafe5-6775-4724-a32c-906b8285950f)

After:
![image](https://github.com/darkreader/darkreader/assets/6305520/d87c547d-a63e-4689-9790-9cc1a2b4d6cc)

2024-05-07 20:32 UTC, oberrich commented
De-uglified `input`s, see refund view:

![image](https://github.com/darkreader/darkreader/assets/6305520/918f0951-96cf-4fa5-a18f-c87a1ae2ef97)
*(before)*

![image](https://github.com/darkreader/darkreader/assets/6305520/3a5a4457-4367-47df-b3db-74463e874241)
*(after)*

2024-05-08 20:46 UTC, alexanderby commented
Could you please share the source CSS colors assigned there (with Dark Reader disabled)? The support for those color mixes was added recently, maybe it should be improved.

2024-05-08 20:47 UTC, alexanderby commented on src/config/dynamic-theme-fixes.config
> +input {
Is there a way to be more specific there (by referencing elements with class names for example).

2024-05-08 21:12 UTC, oberrich commented
Dump of styles (devtools)
```css
.tab_container {
    line-height: 1.15;
    -webkit-text-size-adjust: 100%;
    --animate-duration: 1s;
    --animate-delay: 1s;
    --animate-repeat: 1;
    font-family: PayPalSansSmall-Regular,Helvetica Neue,Arial,sans-serif;
    -webkit-font-smoothing: antialiased;
    --darkreader-inline-outline: initial;
    box-sizing: inherit;
    background: var(--sys-background-surface,#fff);
    padding-bottom: 32px;
}
.tab_container:dark-reader {
    color-scheme: dark !important;
    line-height: 1.15;
    -webkit-text-size-adjust: 100%;
    --darkreader-neutral-background: #131516;
    --darkreader-neutral-text: #d8d4cf;
    --darkreader-selection-background: #004daa;
    --darkreader-selection-text: #e8e6e3;
    --animate-duration: 1s;
    --animate-delay: 1s;
    --animate-repeat: 1;
    color: #e8e6e3;
    -webkit-font-smoothing: antialiased;
    --darkreader-inline-outline: initial;
    box-sizing: inherit;
    font-family: Gadugi !important;
    background: var(--sys-background-surface,#fff);
    padding-bottom: 32px;
}

.listing_bg {
    line-height: 1.15;
    -webkit-text-size-adjust: 100%;
    --animate-duration: 1s;
    --animate-delay: 1s;
    --animate-repeat: 1;
    font-family: PayPalSansSmall-Regular,Helvetica Neue,Arial,sans-serif;
    -webkit-font-smoothing: antialiased;
    --darkreader-inline-outline: initial;
    box-sizing: inherit;
    background-color: #faf8f5;
    height: auto;
}
.listing_bg:dark-reader {
    color-scheme: dark !important;
    line-height: 1.15;
    -webkit-text-size-adjust: 100%;
    --darkreader-neutral-background: #131516;
    --darkreader-neutral-text: #d8d4cf;
    --darkreader-selection-background: #004daa;
    --darkreader-selection-text: #e8e6e3;
    --animate-duration: 1s;
    --animate-delay: 1s;
    --animate-repeat: 1;
    color: #e8e6e3;
    -webkit-font-smoothing: antialiased;
    --darkreader-inline-outline: initial;
    box-sizing: inherit;
    font-family: Gadugi !important;
    height: auto;
    background-color: rgb(40, 32, 20);
}
```

_`:dark-reader` isn't real and merely for distinction_

2024-05-09 16:10 UTC, alexanderby commented
Ah, I thought the `color-mix()` was used there. You can try using `background-color: ${#faf8f5) !important;` instead to make it simpler.

2024-05-09 16:13 UTC, alexanderby requested changes

2024-05-09 16:13 UTC, alexanderby commented on src/config/dynamic-theme-fixes.config
> +input {
I'm afraid that all the inputs will look different when not expected. Please use the selectors that correspond with website's own border styles.

2024-05-09 16:13 UTC, alexanderby commented on src/config/dynamic-theme-fixes.config
> +    background-color: color-mix(in srgb, var(--darkreader-neutral-text) 10%, var(--darkreader-neutral-background) 90%) !important;
Please try simplifying it with `background-color: ${#faf8f5) !important;`.

2024-05-10 13:31 UTC, alexanderby approved these changes

2024-05-10 13:32 UTC, merged