Fix for  eeworld.com.cn
darkreader/darkreader pull request #13123
Opened 2024-08-12 08:57 UTC by felixonmars

Invert logo

2024-08-12 19:04 UTC, Myshor requested changes

2024-08-12 19:04 UTC, Myshor commented on src/config/dynamic-theme-fixes.config
> +eeworld.com.cn
I would add alias *.eeworld.com.cn under
then add needed invert from #13124

2024-09-16 20:26 UTC, felixonmars commented on src/config/dynamic-theme-fixes.config
> +eeworld.com.cn
Updated as requested.

2024-09-19 08:58 UTC, Myshor approved these changes

2024-09-19 09:10 UTC, merged