fixed sidebar on galaxus.de
darkreader/darkreader pull request #13179
Opened 2024-08-26 14:23 UTC by Wargamer-Senpai

- Fixed the issue where a white background appeared when clicking on your profile in dark mode

2024-08-27 09:21 UTC, Myshor requested changes

2024-08-27 09:21 UTC, Myshor commented on src/config/dynamic-theme-fixes.config
> +.sc-fdf7076e-0 {
maybe change this selector to: `#sidebarMenu div`
This class looks like it can be randomly generated name. 😉

2024-08-27 20:28 UTC, Wargamer-Senpai commented
Thanks for your feedback, if fixed the mentioned issues, please check again 😄

2024-08-28 09:21 UTC, Myshor approved these changes

2024-08-28 09:29 UTC, merged