Update dark-sites.config
darkreader/darkreader pull request #13238
Opened 2024-09-11 19:00 UTC by realpixelcode

Added several Mastodon servers with dark themes. Removed Graphene's and Tuta's websites because they're not dark by default.

2024-09-21 10:05 UTC, Myshor requested changes
Fix sorting.

2024-09-21 10:05 UTC, Myshor commented on src/config/dark-sites.config
> +edi.social
not sorted alphabetically

should be before edit-csv.net

2024-09-21 10:05 UTC, Myshor commented on src/config/dark-sites.config
> +mstdn.social
not sorted alphabetically

should be under ms-paint-i.de

2024-09-21 10:05 UTC, Myshor commented on src/config/dark-sites.config
> +universeodon.com
not sorted alphabetically

should be under universe.eveonline.com

2024-09-23 22:41 UTC, realpixelcode commented on src/config/dark-sites.config
> +ard.social
> . is above the letters so it should be above ardov.me

thx, I didn't know that

2024-09-23 22:43 UTC, realpixelcode commented on src/config/dark-sites.config
> +bonn.social
lol, I'm stupid

2024-09-24 11:22 UTC, Myshor approved these changes

2024-09-24 11:23 UTC, merged