Fix for typst.app/universe
darkreader/darkreader pull request #13283
Opened 2024-09-24 14:40 UTC by Andrew15-5

The problem I faced is that `#results li`/`#banner` style inverts the style for all children, which is why I had to _additionally_ invert all of their key children.

Note that the default `filter: invert(100%) hue-rotate(180deg) contrast(90%) !important;` inversion style doesn't look good here, so I used `filter: invert(95%) hue-rotate(180deg) contrast(90%) !important;` instead.

I made a separate `/universe` entry because Typst Universe is a different/isolated website, so it insures that some other `#banner` etc. styles on other pages won't be affected. And the previous SVG fix is more of a global fix (applies to Universe and docs websites).

## Before

https://typst.app/universe/search:

![image](https://github.com/user-attachments/assets/9a5bfd65-4382-4cb5-aaaf-e00da82edd4f)
---

https://typst.app/universe/package/alchemist:

![image](https://github.com/user-attachments/assets/08ec0d3f-6a5a-49da-9503-34b591b57a37)
---

https://typst.app/universe/package/a2c-nums:

![image](https://github.com/user-attachments/assets/c9ca3774-78e8-4d9a-8a1e-f98a2ecd9c05)

## After

https://typst.app/universe/search:

![image](https://github.com/user-attachments/assets/d63b7feb-e288-4643-b857-6ab3ff625fd3)
---

https://typst.app/universe/package/alchemist:

![image](https://github.com/user-attachments/assets/ac7757bf-1a25-41c1-b031-bc9a1f1aecb0)
---

https://typst.app/universe/package/a2c-nums:

![image](https://github.com/user-attachments/assets/0075b920-7553-453a-9ecf-9d0d3af875ee)

2024-09-24 19:21 UTC, Myshor requested changes
It works fine with dark scheme but fixes should work fine with light scheme too and search ends with inverted pictures:
![obraz](https://github.com/user-attachments/assets/a744b062-11ec-4e9e-bdbe-3f5c5ef768ef)

I propose:
```
typst.app/universe

INVERT
img[alt*="icon"]
#results li
#results img
#results .title
#results .description
#banner
#banner .title
#banner .description
#banner .featured-label
#banner .icon

CSS
#banner {
    border: 1px solid !important;
    border-color: lightgray !important;
}
#results li {
    border: 1px solid !important;
    border-color: lightgray !important;
    border-radius: 12px !important;
}

================================


```

It ends with almost the same background as page background for "a2c-nums" and others using the same color but at least doesn't break loading page in light scheme and dark scheme.

In CSS I would add borders that are almost invisible but at least goes around that very dark ones.

Result can be seen below:
![obraz](https://github.com/user-attachments/assets/734949c4-24f5-4a63-bdde-267e8a3e7b1d)
![obraz](https://github.com/user-attachments/assets/4e996a3e-0ccc-4a7f-b84a-3e84e51af55d)

P.S.
`img[alt*="icon"]` inverts all black icons I saw on the mentioned pages.

2024-09-24 20:09 UTC, Andrew15-5 commented
> fixes should work fine with light scheme

There is a light scheme? D: Does it make all websites bright? I did a lot of patches before but never tested that, I didn't even know about this until just now.

> `img[alt*="icon"]` inverts all black icons I saw on the mentioned pages.

Yeah, that's a good catch, didn't notice that.

> It ends with almost the same background as page background for "a2c-nums" and others using the same color but at least doesn't break loading page in light scheme and dark scheme.

I specifically used the `invert(95%)` because uncolored packages are just plain black and one with the background, even though for default theme this is kinda also true. I want them to have a slightly different background so that they are easily distinguished from background/each other. With your proposal, they again go black.

> In CSS I would add borders that are almost invisible but at least goes around that very dark ones.

As a substitution for distinguished background? I didn't think of this, but I guess I can do that, if background change is out of the question. The thin border does add a little bit of accumulative vertical height.

2024-09-24 20:20 UTC, Andrew15-5 commented
![image](https://github.com/user-attachments/assets/af52c7ad-2890-443c-9928-3c1be3f2bbf1)
![image](https://github.com/user-attachments/assets/37e8d464-d46c-441b-9250-acb7665fc498)
![image](https://github.com/user-attachments/assets/7c2b3340-3cf8-499a-aef2-b5de3ad0d4de)

2024-09-24 20:22 UTC, Andrew15-5 commented
> Just be careful... I made some edits with more fixes to my proposal.

Wait, there is more??? /hj

OK, let's read that comment again.

2024-09-24 20:31 UTC, Andrew15-5 commented
I'm not sure about `#categories ul li a`:

![image](https://github.com/user-attachments/assets/7038b32e-c6b3-4de8-9f61-2b7656f8e937)

2024-09-24 20:34 UTC, Andrew15-5 commented
I noticed that after switching to light and then back to dark scheme, the styling breaks and the page needs a reload:

![image](https://github.com/user-attachments/assets/20c5f729-98c0-475f-86cc-a21b9240b8ca)

Maybe a bug or limitation.

2024-09-24 20:43 UTC, Myshor commented
> I'm not sure about `#categories ul li a`:
> 
> ![image](https://private-user-images.githubusercontent.com/37143421/370460845-7038b32e-c6b3-4de8-9f61-2b7656f8e937.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyMTAzNDksIm5iZiI6MTcyNzIxMDA0OSwicGF0aCI6Ii8zNzE0MzQyMS8zNzA0NjA4NDUtNzAzOGIzMmUtYzZiMy00ZGU4LTlmNjEtMmI3NjU2ZjhlOTM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDIwMzQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjMjdjMjBjMmRmMDhiODZjMTE5ZTc0NDM0OTRiM2M4Mzk0ZjcyY2Y3ODY0ZDJkMWJkNThhZDA1Yzc5NWQ4MTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uuUdYqTI0Iq8rVSjhpsHfinT-TFmdnp-n69b1rCC8zk)

For that I am not sure what browser you use but in my Firefox they look fine like screen below:
![obraz](https://github.com/user-attachments/assets/de7334c5-7dd3-4c06-892c-8ec409ebadc2)

That's why I did not touch them.

Even with dark text they looks fine to me.



> I noticed that after switching to light and then back to dark scheme, the styling breaks and the page needs a reload:
> 
> ![image](https://private-user-images.githubusercontent.com/37143421/370461441-20c5f729-98c0-475f-86cc-a21b9240b8ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyMTAzNDksIm5iZiI6MTcyNzIxMDA0OSwicGF0aCI6Ii8zNzE0MzQyMS8zNzA0NjE0NDEtMjBjNWY3MjktOThjMC00NzVmLTg2Y2MtYTIxYjkyNDBiOGNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDIwMzQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwMWI1M2ZhNjUzYWEzMTZlY2I2MmM3M2Y2MzFkMzE5MzQzMWM0MjQ4MzhiYzFlZGE1YjNlNjFlMTg0ZGVmNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zhl5gs-ufF5o1eOtRpzmSDRa1T4i2FIKmtRn6R1sa58)
> 
> Maybe a bug or limitation.

I noticed that too... May be some issue when we invert too much 😂 but most of the people if use light/dark scheme configured for dark reader they do not switch them that often as people doing and checking fixes. (I hope) So minor bug.

The light/dark scheme is mostlu used for this option:
![obraz](https://github.com/user-attachments/assets/30375576-d201-4e82-b557-f72aa6f2e5fc)
![obraz](https://github.com/user-attachments/assets/ee107327-844d-4145-9ab8-ecd41ee0a042)

As it sometime can change dark sites into light ones user can set to change scheme of Dark Reader automaticaly depending on system theme.

Not many people use it but there was some bugs about broken light theme in the past that's why I am trying to check if everything works fine with my PRs and with PRs I review. 😉

2024-09-24 20:47 UTC, Myshor commented
OK... Finish this PR calmly.

I need to switch off. So I will come back tomorrow to that when I will be back to my PC. 😉

2024-09-24 22:12 UTC, Andrew15-5 commented
> That's why I did not touch them.
> 
> Even with dark text they looks fine to me.

Someone linked https://webaim.org/resources/contrastchecker/ from where it is said that black text would have more contrast than the white, so I think I will make it black after all.

> OK... Finish this PR calmly.

This will be the calmest PR in human history!

2024-09-24 22:15 UTC, Andrew15-5 commented
Since I already tested it a few times, I think it should be ready.

2024-09-25 11:07 UTC, Myshor approved these changes

2024-09-25 11:09 UTC, merged

2024-09-25 11:11 UTC, Myshor commented
Done... Thanks for your cooperation and for showing me that I didn't catch I could border something deeper to not use border-radius manually. 😁

2024-09-25 11:18 UTC, Andrew15-5 commented
> for showing me that I didn't catch I could border something deeper to not use border-radius manually.

Yeah, I just thought that it looks weird that an explicit border radius is set when there is already a hover outline that has this style set. That's how I found that the additional line can be removed and CSS blocks merged. I also had `#results li a` at first, but you proposed `#results li`, so this also was a small pointer.