add vudu to dark-sites
darkreader/darkreader pull request #13289
Opened 2024-09-26 02:38 UTC by gordcodes

2024-09-26 20:16 UTC, Myshor requested changes
For https://www.vudu.com/region-error I end with this region error so I can not check.

For X I can confirm even by this video: https://www.youtube.com/watch?v=kEx5WbFwHqY that it's not always dark and light mode can be selected and used by default!

So X must be removed for sure.

2024-09-27 10:24 UTC, gordcodes commented
I removed X, I had no idea there was a darkness setting that persisted across devices

2024-09-27 14:12 UTC, Myshor approved these changes

2024-09-27 14:31 UTC, Myshor commented
OK... Installed some VPN for a while and didn't find any switching to light mode on vudu so I will merge. 😉

2024-09-27 14:31 UTC, merged