Update desmos.com site section in dynamic-theme-fixes.config file
darkreader/darkreader pull request #13286
Opened 2024-09-25 16:54 UTC by mndtr

# Before:
![ДО](https://github.com/user-attachments/assets/04582614-3e3d-4662-abfa-8539711d233c)
# After:
![ПОСЛЕ](https://github.com/user-attachments/assets/5e7eb3c2-fa2f-4cc2-bdae-971501c1c2da)
# What I did
I just added some elements to ```INVERT``` in dynamic theme config file at ```desmos.com``` section.
Maybe there is a more neat way to fix this but I chosen the fastest one because this white line annoyed me while I just wanted to use desmos

2024-09-25 18:12 UTC, mndtr commented
Just noticed that it causes some problems with add menu. I don't really use this menu but this defenitely not how it should work. Will try to fix this out but not sure this I can... Maybe it looks better but break site functionality. Hope someone will help if I will not fix it.
# Screenshot:
![изображение](https://github.com/user-attachments/assets/4bb154d6-083f-4a25-806c-ad0a258e5811)

2024-09-26 20:24 UTC, Myshor commented
Can you share the URL I could check how it looks like? Maybe I will find some alternative solution that won't mess with the menu. 😉

2024-09-27 02:29 UTC, mndtr commented
https://www.desmos.com/calculator

2024-09-27 12:08 UTC, mndtr commented
> Can you share the URL I could check how it looks like? Maybe I will find some alternative solution that won't mess with the menu. 😉

https://www.desmos.com/calculator

2024-09-27 14:10 UTC, Myshor requested changes
Remove all added Inverts and instead of that add this to the end of CSS section. 😉

```
.dcg-expression-top-bar {
    background: var(--darkreader-neutral-background) !important;
}
```

This will work better and not mess the menu appearing after pressing plus button.

2024-09-27 14:16 UTC, mndtr commented
> Remove all added Inverts and instead of that add this to the end of CSS section. 😉
> 
> ```
> .dcg-expression-top-bar {
>     background: var(--darkreader-neutral-background) !important;
> }
> ```
> 
> This will work better and not mess the menu appearing after pressing plus button.

Wow thanks! Works nice and look cool. Finally my desmos really good dark. Hope your changes will approved and added to DarkReader

2024-09-27 14:18 UTC, Myshor commented
> Wow thanks! Works nice and look cool. Finally my desmos really good dark. Hope your changes will approved and added to DarkReader

I though you will edit your PR and I will merge it as yours. 😉

2024-09-27 14:22 UTC, Myshor commented
@mndtr  Just check if you pushed your changes. Because I see review request but I do not see any changes.

2024-09-27 15:11 UTC, mndtr commented
@Myshor ok I changed .config file how you adviced

2024-09-27 15:42 UTC, Myshor approved these changes

2024-09-27 15:43 UTC, merged