Show different Extension icons for Disabled, Enabled, Dark and Light Modes
darkreader/darkreader pull request #13596
Opened 2024-12-08 07:01 UTC by Akshat-Shu

* Adds new grayscale icons for both icons which were previously used
* When extension is disabled, grayscale icons are used
* type of icon depends on the theme user has currently chosen

See Video for reference:
![Reference Video](https://imgur.com/ChcBHXJ)

2024-12-19 03:22 UTC, Akshat-Shu commented
@alexanderby Are any changes required?

2024-12-19 18:42 UTC, alexanderby requested changes

2024-12-19 18:42 UTC, alexanderby commented on src/background/icon-manager.ts
> +import { FilterMode } from 'generators/css-filter';
Please use relative file paths (`../`). Please remove spaces between brackets according to our code style (`npm run code-style`).

2024-12-19 18:42 UTC, alexanderby commented on src/background/icon-manager.ts
> +        if(IconManager.iconState.active) {
Please put a space after `if`.

2024-12-19 18:42 UTC, alexanderby commented on src/background/icon-manager.ts
> +        this.setTheme(UserStorage.settings.theme.mode);
Please try avoiding using the global object here. Maybe it's possible to pass the theme as an argument or have a single method like `setIcon({dark: true, active: true});`.

2024-12-19 18:42 UTC, alexanderby commented on src/background/icon-manager.ts
> +            chrome.browserAction.setIcon({
Try calling the `chrome.browserAction.setIcon` once outside of `if-else`. Assign `path` variable in `if-else` or `x ? y : z` depending on what will be more readable.

2024-12-22 17:43 UTC, Akshat-Shu commented
@alexanderby Please confirm the changes made

2024-12-26 10:40 UTC, Akshat-Shu commented
@alexanderby Please review the changes made

2024-12-26 11:52 UTC, alexanderby commented
@Akshat-Shu Sorry, I'm on a holiday. Don't worry, it should get into the next release. We are almost there, looks good. Please fix a few code style errors, you can see them [here](https://github.com/darkreader/darkreader/actions/runs/12419651078/job/34883883083?pr=13596) or run `npm run code-style`.

2024-12-31 03:18 UTC, Akshat-Shu commented
@alexanderby Please find the changes above

2025-01-05 10:08 UTC, Akshat-Shu commented
@alexanderby Please confirm if everything is alright now

2025-01-06 14:16 UTC, alexanderby approved these changes
Looks good, thank you. I only renamed some icons back to prevent triggering additional store reviews due to changes in manifest.json file.

2025-01-06 14:17 UTC, alexanderby commented on src/background/icon-manager.ts
> +            path: path,
A minor note: in ES6+ you can write it in a single line `{path}`.

2025-01-06 14:18 UTC, merged

2025-03-18 04:47 UTC, iamkroot commented
Looks like this feature got disabled in https://github.com/darkreader/darkreader/commit/064c4eff2016f3207e432449412d2b1e54391310 
@alexanderby could you please share the reason for disabling it?

2025-03-18 11:41 UTC, alexanderby commented
@iamkroot On top of that per-site icon state was added, and 3 icon states have become too confusing. It will be simplified in one of the future releases.

2025-03-19 04:04 UTC, Akshat-Shu commented
Hey! Please elaborate on what modifications are to be made so that I can start working upon them.