Fix CW PSA icons for all instances
darkreader/darkreader pull request #13684
Opened 2024-12-31 08:05 UTC by jerko-lenex

#12526 already added NA to the config, this PR would enable white icons for all CW PSA instances.

2024-12-31 20:31 UTC, Myshor requested changes

2024-12-31 20:31 UTC, Myshor commented on src/config/dynamic-theme-fixes.config
> +*.myconnectwise.net
Sitefixes must be sorted alphabetically.
When you remove main URL and change it to another then the fix must be moved - in this case before `*.myworkday.com`

2025-01-02 07:58 UTC, jerko-lenex commented on src/config/dynamic-theme-fixes.config
> +*.myconnectwise.net
Thank you for the feedback, I've moved the entry to before `*.myworkday.com`.

2025-01-02 13:14 UTC, Myshor approved these changes

2025-01-02 13:16 UTC, Myshor approved these changes

2025-01-02 13:17 UTC, merged