Fix render bug for protected sites
darkreader/darkreader pull request #3549
Opened 2020-08-29 19:41 UTC by Gusted

- Real-time site-toggle disable according isProtected logic and `enableForProtectedPages` option.
- tab.isProtected should not use `enableForProtectedPages` option as it doesn't get up-to-date data and will return the old value.
- Resolves #3548

2020-08-30 11:44 UTC, Gusted commented
@erkinalp 
Commit https://github.com/darkreader/darkreader/pull/3549/commits/fb99c33727d80b8a26ecc910a360c9c61f315ce4 fixed this reversed behavior and is now behaving how it should be.

2020-08-30 14:55 UTC, erkinalp approved these changes
thanks

2020-08-30 17:29 UTC, erkinalp commented
another bug: non-protected pages cannot be toggled now if you disable "enable on protected pages".

2020-08-30 17:31 UTC, Gusted commented
Shit here we go again.

2020-08-30 17:45 UTC, Gusted commented
@erkinalp 
Are you sure? I tried a fresh `npm run debug` of this branch and it just behaves how it should be. Maybe something in your sitelist?

2020-08-30 17:49 UTC, erkinalp commented
Certainly not. I tried a `npm run release`, though.

2020-08-30 18:20 UTC, Gusted commented
> You know, it is a thing that some things only fail in release builds.

You know, the thing with our build workflow. The output of the code is always the same and gives identical(Other than some more debug info and a inline-source-map that doesn't affect the actual code) output and results.

 

> Certainly sure. I tried a `npm run release`,

Noppes and nana, it still works. I suggest to remove the extension and than re-side-load it.

2020-08-30 18:53 UTC, erkinalp commented
Re-side loaded but still having the same problem.

2020-08-30 19:26 UTC, Gusted commented
What if you try to sideload [this version of the branch](https://github.com/darkreader/darkreader/files/5147339/darkreader.zip)

2020-08-30 20:57 UTC, erkinalp commented
That version fixed the problem :1st_place_medal:

2020-08-30 20:58 UTC, Gusted commented
Well, that was commit https://github.com/darkreader/darkreader/pull/3549/commits/6b309fdddc5b60d606da78d4b961bdbc03dea137 but than `npm run debug`

2020-08-31 08:34 UTC, alexanderby requested changes

2020-08-31 08:34 UTC, alexanderby commented on src/ui/popup/components/site-toggle/index.tsx
> +        data.settings.enableForProtectedPages ? true : !tab.isProtected
```javascript
(data.settings.enableForProtectedPages || !tab.isProtected)
```

2020-09-01 14:31 UTC, alexanderby approved these changes

2020-09-01 14:32 UTC, merged

2025-01-15 18:17 UTC, Scutua approved these changes