Wait for link element to be loaded.
darkreader/darkreader pull request #3552
Opened 2020-08-30 12:07 UTC by Gusted

- Wait until the link element has been loaded.
- Resolves #835

2020-08-30 12:07 UTC, Gusted commented
However, this should resolve the error and handling(what's being done). It doesn't show any progress on the styles itself.

2020-09-02 06:31 UTC, erkinalp approved these changes

2020-09-02 07:09 UTC, Gusted commented
@erkinalp Does it works for you? For me it's still persists as problem.

2020-09-24 10:56 UTC, erkinalp approved these changes

2020-09-24 10:56 UTC, erkinalp commented on src/inject/dynamic-theme/css-rules.ts
> +                    iterateCSSRules(rule.styleSheet.cssRules, iterate);
thanks

2020-09-24 10:59 UTC, Gusted commented on src/inject/dynamic-theme/css-rules.ts
> +                    iterateCSSRules(rule.styleSheet.cssRules, iterate);
It's still a POC as it doesn't work for me so not sure where the fault relies.

2020-09-24 17:28 UTC, 11bit commented
Hey guys, I have experimented a bit with this issue and found the change that seems to be the cause of the problem: https://github.com/darkreader/darkreader/commit/7185820f7d6865dbd908ee3196eaf080bf3c90b4#diff-3d04f9c5378d3d93c42df303885b05a5L144

Probably the change from `if (cssRules == null || accessError) {` to `if ((cssRules && !accessError) || isStillLoadingError(accessError)) {` is not correct because cssRules for links in load state in Chrom is null.

What do you think about changing the condition like this:
```diff
index 2b73dfc0..04d703d8 100644
--- a/src/inject/dynamic-theme/style-manager.ts
+++ b/src/inject/dynamic-theme/style-manager.ts
@@ -143,7 +143,7 @@ export function manageStyle(element: StyleElement, {update, loadingStart, loadin
                 logWarn(accessError);
             }

-            if ((cssRules && !accessError) || isStillLoadingError(accessError)) {
+            if ((cssRules === null && !accessError) || isStillLoadingError(accessError)) {
                 try {
                     await linkLoading(element);
                 } catch (err) {
```

2020-09-24 17:38 UTC, Gusted commented
`  if ((cssRules === null && !accessError)`

Hmm seems it's now checking again if it's null instead of checking if it exist. That's inverted logic. @alexanderby?

2020-09-24 17:57 UTC, erkinalp approved these changes

2020-09-24 18:21 UTC, alexanderby commented
Hmm, sounds reasonable, it used to check for `null` before, maybe I was not attentive. But then surprising how it works. You can simplify the condition with `if (!(cssRules || accessError) || isStillLoadingError(accessError))...`.

2020-09-24 18:27 UTC, alexanderby requested changes

2020-09-24 18:27 UTC, alexanderby commented on src/inject/dynamic-theme/css-rules.ts
> +    forEach(rules, async (rule) => {
Is `async` needed there?

2020-09-24 18:28 UTC, Gusted commented on src/inject/dynamic-theme/css-rules.ts
> +    forEach(rules, async (rule) => {
Not anymore

2020-09-24 19:30 UTC, alexanderby commented
Works unstable for me at https://docs.python.org/3/

2020-10-21 21:46 UTC, Gusted commented
Chromium is having a bug, which I partially understand but can't explain.  Tried to in https://github.com/darkreader/darkreader/pull/3552/commits/6d00650e25caaff8f93e9beb69d72689f3b9fe22

2020-10-21 21:47 UTC, Gusted commented
But their still seems to be some condition that the `sync` and `async` of iterateCSSType is conflicting and therefor still not loaded correctly.

2020-11-13 06:52 UTC, erkinalp approved these changes

2021-06-22 17:54 UTC, Gusted commented
Very unreliable - Overseeded by #6102

2021-06-22 17:54 UTC, closed without merging