Fix LinkedIn card prompt background
darkreader/darkreader pull request #3614
Opened 2020-09-08 17:24 UTC by BurnhamG

Before: 
![firefox_RgTz3pfXtg](https://user-images.githubusercontent.com/18239224/92508316-0fde3800-f1ce-11ea-9679-50c72e0153f5.png)

After:
![firefox_oDl3bZXSdl](https://user-images.githubusercontent.com/18239224/92508327-140a5580-f1ce-11ea-80ae-6867ef83f37a.png)

2020-09-08 17:34 UTC, Gusted commented
Hi @BurnhamG!

Does the element have by default no background-color?

Regards,
Gusted

2020-09-08 18:24 UTC, BurnhamG commented
Hi @Gusted, the default was to have a linear gradient. I must apologize, I jumped the gun a bit with this PR. My latest commit preserves the linear gradient that was on the original card, using the correct CSS variables. Here's a new after image:

![image](https://user-images.githubusercontent.com/18239224/92513847-9139c880-f1d6-11ea-957c-f6fa664d37a5.png)

2020-09-09 08:04 UTC, Gusted requested changes

2020-09-09 08:04 UTC, Gusted commented on src/config/dynamic-theme-fixes.config
> +  background: linear-gradient(
You can use the linear-gradient on 1 line. No need for spaces of this CSS property.

2020-09-09 20:37 UTC, merged