feat: add a bunch of dark sites
darkreader/darkreader pull request #3770
Opened 2020-10-03 01:17 UTC by pizzafox

Adds a bunch of dark sites I've been collecting in my personal site list over the years.

2020-10-03 23:51 UTC, Gusted requested changes

2020-10-03 23:51 UTC, Gusted commented on src/config/dark-sites.config
> +colab.research.google.com
Not dark by default

2020-10-03 23:51 UTC, Gusted commented on src/config/dark-sites.config
> +create-react-app.dev
Not dark by default

2020-10-03 23:51 UTC, Gusted commented on src/config/dark-sites.config
> +cutestrap.com
Not dark by default

2020-10-03 23:51 UTC, Gusted commented on src/config/dark-sites.config
> +discord.js.org
Not dark by default

2020-10-03 23:51 UTC, Gusted commented on src/config/dark-sites.config
> +dormdev.com
Not dark by default

2020-10-03 23:51 UTC, Gusted commented on src/config/dark-sites.config
> +duckduckgo.com
Not dark by default

2020-10-03 23:51 UTC, Gusted commented on src/config/dark-sites.config
> +klasa.js.org
Not dark by default

2020-10-03 23:51 UTC, Gusted commented on src/config/dark-sites.config
> +material.angular.io
Not dark by default

2020-10-03 23:51 UTC, Gusted commented on src/config/dark-sites.config
> +messages.google.com
Not dark by default

2020-10-03 23:51 UTC, Gusted commented on src/config/dark-sites.config
> +mikro-orm.io
Not dark by default

2020-10-03 23:51 UTC, Gusted commented on src/config/dark-sites.config
> +pcpartpicker.com
Not dark by default

2020-10-03 23:51 UTC, Gusted commented on src/config/dark-sites.config
> +twitch.tv
Dark detected by system colors.

2020-10-03 23:51 UTC, Gusted commented on src/config/dark-sites.config
> +twitter.com
Dark detected by system colors.

2020-10-03 23:51 UTC, Gusted commented on src/config/dark-sites.config
> +typescriptlang.org/docs
Not dark by default

2020-10-03 23:51 UTC, Gusted commented on src/config/dark-sites.config
> +vercel.com
Not dark by default

2020-10-04 00:30 UTC, pizzafox commented
@Gusted what's the qualifier for sites marked as "dark detected by system colors", and why is this a bad thing?

2020-10-04 12:45 UTC, Gusted commented
> @Gusted what's the qualifier for sites marked as "dark detected by system colors", and why is this a bad thing?

Dark by default no matter what.

That means if the site is checking if the user preferred dark colors. Than if the user has preferred light colors the site will have a light theme and dark reader will say it's in the dark config and not darken it. It's not dark by default

2020-10-04 12:45 UTC, merged