Google Translate Verified Translation button fix
darkreader/darkreader pull request #3777
Opened 2020-10-04 06:44 UTC by kaixokkiten

If the page is zoomed in, the verified translation button would be zoomed in but the right color. This fixes it.

2020-10-04 12:42 UTC, Gusted commented
Hi @kaixokkiten!

I don't see a difference of the color when zoomed in.

Regards,
Gusted

2020-10-04 23:48 UTC, kaixokkiten commented
No, the color is right! It is just that the verified checkmark is zoomed in because it is a span with a background that changes size. 
![image](https://user-images.githubusercontent.com/18796736/95029976-20bd8480-067a-11eb-80a1-8470ab2d89e8.png)
with my edit: 
![image](https://user-images.githubusercontent.com/18796736/95030016-69753d80-067a-11eb-9554-274cb7d454a6.png)
it appears to have something to do with the default zoom in chrome being more than 100% or zooming in, or reducing the width of the screen to less than 720 causing some weirdness that resets the size of the checkmark.

2020-10-05 07:18 UTC, Gusted requested changes

2020-10-05 07:18 UTC, Gusted commented on src/config/dynamic-theme-fixes.config
> +    background-size: cover;
Add `!important;`

2020-10-05 23:28 UTC, likuilin commented
Hi, I'm running into this issue too, and I can reproduce it on Chrome 85.0.4183.121: 

* Create a new profile
* Install Dark Reader
* Go to https://translate.google.com/
* Put in a common translation, like English to Spanish word "yes"
* Zoom in slightly using Ctrl-+

The above patch does fix it. Since `.trans-verified-button` is the most specific CSS selector, adding `!important` wouldn't change anything, but it does help with futureproofing the fix.

2020-10-06 16:09 UTC, merged