Fixes for worldcubeassociation.org
darkreader/darkreader pull request #4329
Opened 2020-11-30 09:19 UTC by viktorzenk

22 flags were displayed incorrectly, which was fixed in a somewhat janky/hardcoded way. Example page with flags visible: https://www.worldcubeassociation.org/results/rankings/333/single?region=world&show=by+region
Fixed event selectors being indiscernible between checked and unchecked. Example: https://www.worldcubeassociation.org/profile/edit?section=preferences (I don't think it's visible anywhere that doesn't require an account).

2020-11-30 17:06 UTC, Yash-Singh1 requested changes

2020-11-30 17:06 UTC, Yash-Singh1 commented on src/config/dynamic-theme-fixes.config
> +.flag-icon-jm{background-image: url(/packs/media/4x3/jm-6bb96bbc.svg);}
Try to keep bracket spacing:
```css
.flag-icon-pl{background-image: url(/packs/media/4x3/pl-7ea4b5b2.svg);}
```
would become
```css
.flag-icon-pl { background-image: url(/packs/media/4x3/pl-7ea4b5b2.svg); }
```
See this for more guidelines: https://www.drupal.org/docs/develop/standards/css/css-formatting-guidelines#s-exceptions-and-slight-deviations

2020-11-30 18:40 UTC, Gusted commented
HI @viktorzenk!

I don't see the flags being displayed incorrectly.

Regards,
Gusted

2020-11-30 19:01 UTC, viktorzenk commented
> HI @viktorzenk!
> 
> I don't see the flags being displayed incorrectly.
> 
> Regards,
> Gusted

Hmm, that's odd. To me, the flags are fine for a second or so, then some of the flags are loaded as a different background-image, see screenshot below.

![image](https://user-images.githubusercontent.com/38689420/100652104-b574f380-3346-11eb-9c24-0e931cffb6e8.png)

2020-11-30 19:04 UTC, Gusted commented
Weird, anyway every selector should be listed under the 
`IGNORE IMAGE ANALYSIS` section in order to be not styled at all.
So `CSS` -> `IGNORE IMAGE ANALYSIS` and just the CSS selectors.

2020-11-30 19:15 UTC, viktorzenk commented
Yeah, I initially tried this:

```
================================

worldcubeassociation.org

IGNORE IMAGE ANALYSIS
.flag-icon

================================
```
but that did not work. Is that the way I should use it, or am I misunderstanding? :)

2020-11-30 19:24 UTC, Yash-Singh1 commented
> Yeah, I initially tried this:
> 
> ```
> ================================
> 
> worldcubeassociation.org
> 
> IGNORE IMAGE ANALYSIS
> .flag-icon
> 
> ================================
> ```
> 
> but that did not work. Is that the way I should use it, or am I misunderstanding? :)

Same here

2020-11-30 19:26 UTC, Gusted commented
Yes, all incorrect flags needs a seperate CSS e.g. poland `.flag-icon-pl` because the selectors needs to be matched exactly to the element and not a parent of it.

2020-12-01 20:38 UTC, Yash-Singh1 commented
The following works:
```
================================

worldcubeassociation.org

IGNORE IMAGE ANALYSIS
.flag-icon-pl
.flag-icon-kr
.flag-icon-fi
.flag-icon-jp
.flag-icon-ru
.flag-icon-si
.flag-icon-co
.flag-icon-lt
.flag-icon-sk
.flag-icon-bg
.flag-icon-ve
.flag-icon-ge
.flag-icon-ec
.flag-icon-pk
.flag-icon-uy
.flag-icon-mg
.flag-icon-pa
.flag-icon-cy
.flag-icon-bh
.flag-icon-mt
.flag-icon-bt
.flag-icon-jm

================================
```
![Screenshot from 2020-12-01 12-38-31](https://user-images.githubusercontent.com/53054099/100794263-29101280-33d2-11eb-93c0-e5443582abbe.png)

2020-12-01 20:54 UTC, Gusted commented
> The following works:
> 
> ```
> ================================
> 
> worldcubeassociation.org
> 
> IGNORE IMAGE ANALYSIS
> .flag-icon-pl
> .flag-icon-kr
> .flag-icon-fi
> .flag-icon-jp
> .flag-icon-ru
> .flag-icon-si
> .flag-icon-co
> .flag-icon-lt
> .flag-icon-sk
> .flag-icon-bg
> .flag-icon-ve
> .flag-icon-ge
> .flag-icon-ec
> .flag-icon-pk
> .flag-icon-uy
> .flag-icon-mg
> .flag-icon-pa
> .flag-icon-cy
> .flag-icon-bh
> .flag-icon-mt
> .flag-icon-bt
> .flag-icon-jm
> 
> ================================
> ```
> 
> ![Screenshot from 2020-12-01 12-38-31](https://user-images.githubusercontent.com/53054099/100794263-29101280-33d2-11eb-93c0-e5443582abbe.png)

Correct

2020-12-01 22:52 UTC, Yash-Singh1 requested changes
Move the selectors into `IGNORE IMAGE ANALYSIS`

2020-12-01 22:52 UTC, Yash-Singh1 commented on src/config/dynamic-theme-fixes.config
> +
Move the selectors into `IGNORE IMAGE AnALYSIS`
```suggestion
.event-checkbox input[type="checkbox"] + i.cubing-icon, .event-checkbox input[type="radio"] + i.cubing-icon, .event-radio input[type="checkbox"] + i.cubing-icon, .event-radio input[type="radio"] + i.cubing-icon{
    color: rgba(0,0,0,1);
}

IGNORE IMAGE ANALYSIS
.flag-icon-pl
.flag-icon-kr
.flag-icon-fi
.flag-icon-jp
.flag-icon-ru
.flag-icon-si
.flag-icon-co
.flag-icon-lt
.flag-icon-sk
.flag-icon-bg
.flag-icon-ve
.flag-icon-ge
.flag-icon-ec
.flag-icon-pk
.flag-icon-uy
.flag-icon-mg
.flag-icon-pa
.flag-icon-cy
.flag-icon-bh
.flag-icon-mt
.flag-icon-bt
.flag-icon-jm

```

2021-01-08 10:16 UTC, merged