Add engine + mode into html classname
darkreader/darkreader pull request #4860
Opened 2021-01-23 22:15 UTC by Gusted

- Add an class into `HTML` element to specify engine + mode.
- This enables to specify the mode inside the dynamic fixes to solve certain problems.
- Let's users solve certain dark-mode CSS problems for their sites locally.
- Resolves #4835

2021-02-23 23:26 UTC, KaKi87 commented
From what I'm seeing, the attribute key is dynamic, why ? That makes it difficult to select in CSS

2021-02-24 12:11 UTC, Gusted commented
> From what I'm seeing, the attribute key is dynamic, why ? That makes it difficult to select in CSS

I think I've made a little mistake in the code, it should be `data-darkreader="'Engine'-'Filter'"` so it could become `data-darkreader="dynamic-dark"` and could easily be targeted with CSS.

2021-02-24 12:53 UTC, KaKi87 commented
I think the JS misses the dash between engine and mode, and perhaps you forgot to update the test suite ^^

2021-03-29 17:11 UTC, alexanderby requested changes
I would suggest to use two attributes: `data-darkreader-mode` (dynamic, static, filter) and `data-darkreader-scheme` (dark, dimmed). So it will be possible to use it in sites fixes (e.g. `[data-darkreader-scheme="dark"] body { color: black; }`) or maybe it will be simpler for those, who would like to use it somehow in their website's stylesheets.

2021-03-30 18:17 UTC, alexanderby requested changes
I don't remember if I mentioned, when 5.0 will be about to be released, "engine" will become "mode" with "dynamic", "static" and "filter" values ("svgFilter" as a filter option); "mode" will become "scheme" with "dark" and "dimmed" values (or maybe "light", but people often get confused when it's light mode or when the extension is off).

2021-03-30 18:17 UTC, alexanderby commented on src/inject/dynamic-theme/index.ts
> +        document.documentElement.setAttribute('data-darkreader-mode', filter.engine);
`filter.engine` will return `dynamicTheme`, which is a bit odd, so let's use just `'dynamic'`.

2021-03-30 18:17 UTC, alexanderby commented on src/inject/index.ts
> +            createOrUpdateStyle(css, 'static');
`case 'add-css-filter':` should use `'filter'` too, so you will have to split the condition.

2021-03-30 19:01 UTC, Gusted commented
> I don't remember if I mentioned, when 5.0 will be about to be released, "engine" will become "mode" with "dynamic", "static" and "filter" values ("svgFilter" as a filter option); "mode" will become "scheme" with "dark" and "dimmed" values (or maybe "light", but people often get confused when it's light mode or when the extension is off).

That sounds a lot more logical that naming. Just like renaming the current `Filter` variable within the source code to `theme` so it will be separated.

Thereby dimmed is also pretty neat as with the current settings it will be more dimmed than when it's off.

2021-03-30 19:45 UTC, merged