Update dynamic-theme-fixes.config
darkreader/darkreader pull request #5316
Opened 2021-03-23 08:52 UTC by treufuss

Fix background of QR code used for login with smartphone

2021-03-23 09:31 UTC, AndrewDaGuy requested changes
Gusted likes non-hard coded colours, perhaps set it to `${white}`?

2021-03-23 10:11 UTC, treufuss commented
> Gusted likes non-hard coded colours, perhaps set it to `${white}`?

I think it has to be hard coded in this case. The (black) QR code is a png with a transparent background, so i want to set the background of the surrounding div to white in order to make the QR code always visible.

![QRExample](https://user-images.githubusercontent.com/46525924/112129986-3ee75480-8bc8-11eb-8fba-a919443538d9.png)

2021-03-23 17:11 UTC, AndrewDaGuy commented
> I think it has to be hard coded in this case. The (black) QR code is a png with a transparent background, so i want to set the background of the surrounding div to white in order to make the QR code always visible.
> 
> ![QRExample](https://user-images.githubusercontent.com/46525924/112129986-3ee75480-8bc8-11eb-8fba-a919443538d9.png)

Maybe just invert the QR code?

2021-03-23 20:44 UTC, Gusted commented
> @treufuss Maybe just invert the QR code?

Andrew, I just like to suggest to read this sentence once again. With a special note how QR code scanning works ;)

2021-03-23 20:44 UTC, Gusted commented on src/config/dynamic-theme-fixes.config
> +  background-color: #fff !important;
4 Indents & the hard coded color is good as it could otherwise break the QR code implementation

2021-03-23 23:00 UTC, AndrewDaGuy approved these changes
Andrew Approved :+1:, just finish the changes Gusted requested ;]

2021-06-03 07:21 UTC, Gusted commented on src/config/dynamic-theme-fixes.config
> +  background-color: #fff !important;
```suggestion
    background-color: #fff !important;
```

2021-06-03 07:21 UTC, Gusted approved these changes

2021-06-03 07:25 UTC, merged