Update dynamic-theme-fixes.config
darkreader/darkreader pull request #5426
Opened 2021-04-01 16:57 UTC by mezeraj

Fixed the dynamic theme issues that weren't changing colors in dark mode.

2021-04-01 17:03 UTC, mezeraj commented
This is to fix [issue #2717](https://github.com/darkreader/darkreader/issues/2717). I was unsure how to link it or if a moderator did that

2021-04-01 17:17 UTC, AndrewDaGuy commented
resolved #2717

2021-04-01 17:45 UTC, mezeraj commented
Resolves [#2717](https://github.com/darkreader/darkreader/issues/2717)

2021-04-01 18:35 UTC, Gusted requested changes

2021-04-01 18:35 UTC, Gusted commented on src/config/dynamic-theme-fixes.config
> +    color: var(--darkreader-neutral-background) !important;
Should the text-color of this element matches the dynamic value of background?

2021-04-01 18:35 UTC, Gusted commented on src/config/dynamic-theme-fixes.config
> +.atwiki-contents-shadow {
```suggestion
.atwiki-contents-shadow, 
.main_wrapper {
```

2021-04-01 18:35 UTC, Gusted commented on src/config/dynamic-theme-fixes.config
> +.main_wrapper {
You can remove this entry here, when you've merged the suggestion.

2021-06-03 07:22 UTC, Gusted approved these changes

2021-06-03 07:26 UTC, merged