Fix for monta.ir
darkreader/darkreader pull request #5476
Opened 2021-04-05 17:29 UTC by MiliAxe

- Fix white images
- Fix images being black (almost transparent) in problems/choices/notes.
- Fix the problem of the answer sheet being white by default
- Fix graphs being white

2021-04-05 18:49 UTC, Gusted commented on src/config/dynamic-theme-fixes.config
> + background-image: none; !important
```suggestion
    background-image: none !important;
```

2021-04-05 18:49 UTC, Gusted requested changes
See suggestion.

2021-04-05 19:41 UTC, MiliAxe commented
Thanks for the suggestion.
The problem has been resolved.

2021-04-06 11:38 UTC, Gusted approved these changes
Thank you!

2021-04-06 11:38 UTC, merged