ithardware.pl home and forum
darkreader/darkreader pull request #5682
Opened 2021-04-29 16:47 UTC by FadeMind

- https://ithardware.pl/
- https://forum.ithardware.pl/

![20210429-1619714429-001](https://user-images.githubusercontent.com/9846948/116587827-1ff08680-a91b-11eb-8ed5-a5c66e1e9b04.png)
![20210429-1619714417-001](https://user-images.githubusercontent.com/9846948/116587829-2121b380-a91b-11eb-952b-22d29242ce48.png)
![20210429-1619714768-001](https://user-images.githubusercontent.com/9846948/116587891-2ed73900-a91b-11eb-9d33-3a14a1a15d29.png)

2021-04-29 17:27 UTC, FadeMind commented
![20210429-1619717176-001](https://user-images.githubusercontent.com/9846948/116592992-e91d6f00-a920-11eb-8347-e738d1a3403d.png)
![20210429-1619717166-001](https://user-images.githubusercontent.com/9846948/116592994-e9b60580-a920-11eb-9fc0-fc4042b090e9.png)
![20210429-1619717150-001](https://user-images.githubusercontent.com/9846948/116592997-ea4e9c00-a920-11eb-8ea3-e3ae5b51df89.png)

2021-04-29 20:17 UTC, Gusted commented on src/config/dynamic-theme-fixes.config
> +    color: #fff !important;
👀 `var(--darkreader-neutral-text)`

2021-04-30 05:03 UTC, FadeMind commented on src/config/dynamic-theme-fixes.config
> +    color: #fff !important;
thanks

2021-04-30 05:35 UTC, FadeMind commented
https://www.trojmiasto.pl/
![20210430-1619760806-001](https://user-images.githubusercontent.com/9846948/116653005-a2626000-a986-11eb-98ae-a8caca859449.png)

2021-04-30 07:11 UTC, FadeMind commented
https://www.businessinsider.com/?IR=C
https://businessinsider.com.pl
https://businessinsider.co.za
https://businessinsider.es
https://businessinsider.jp
https://businessinsider.mx
https://insider.com
https://it.businessinsider.com

![20210430-1619764891-001](https://user-images.githubusercontent.com/9846948/116660928-fc1d5700-a993-11eb-9236-37a0bea19de0.png)
![20210430-1619764865-001](https://user-images.githubusercontent.com/9846948/116660930-fcb5ed80-a993-11eb-81fe-177900766129.png)
![20210430-1619764854-001](https://user-images.githubusercontent.com/9846948/116660932-fd4e8400-a993-11eb-863c-0f7c811c5a85.png)
![20210430-1619764764-001](https://user-images.githubusercontent.com/9846948/116660933-fd4e8400-a993-11eb-81f3-046a90878c09.png)

etc.

2021-04-30 07:52 UTC, FadeMind commented
- https://wyborcza.biz/Gieldy/0,114514,,,,WIG.html
- https://wyborcza.biz/Waluty/0,111138,8932151,,,Kursy_srednie_walut_NBP,A.html#TRNavSST
- https://wyborcza.pl/0,0.html

![20210430-1619767587-001](https://user-images.githubusercontent.com/9846948/116665129-a6e44400-a999-11eb-96c4-cb4486fb2f5b.png)
![20210430-1619767455-001](https://user-images.githubusercontent.com/9846948/116665134-a77cda80-a999-11eb-9ef7-9b3c64004083.png)
![20210430-1619767447-001](https://user-images.githubusercontent.com/9846948/116665136-a77cda80-a999-11eb-8eda-bed33d4a4e54.png)

2021-04-30 10:25 UTC, Gusted commented on src/config/dynamic-theme-fixes.config
> +businessinsider.com
Yeez so many sites, just trow an 

```
businessinsider.*
```

2021-04-30 10:25 UTC, Gusted commented on src/config/dynamic-theme-fixes.config
> +    var(--darkreader-neutral-text) !important;
this ain't working.

2021-04-30 11:40 UTC, FadeMind commented
![20210430-1619782558-001](https://user-images.githubusercontent.com/9846948/116690354-8d52f480-a9b9-11eb-91cf-b9fb66ffb1d8.png)

2021-04-30 11:40 UTC, FadeMind commented on src/config/dynamic-theme-fixes.config
> +businessinsider.com
done 😁

2021-04-30 11:41 UTC, FadeMind commented on src/config/dynamic-theme-fixes.config
> +    var(--darkreader-neutral-text) !important;
`a[data-mentionid]`

2021-04-30 11:46 UTC, Gusted requested changes
A lot of this images are already inverted by default. I'm not sure how this isn't the case for you as this patch breaks more than it fixes.

2021-04-30 12:00 UTC, FadeMind commented
@Gusted business insider without fixes use black instead white. I can move them to another separated pr if you like. 
I used selectors only needed to invert. Nothing else. (logos, icons). 
Your call.

2021-04-30 12:16 UTC, FadeMind commented
Default - no changes applied
https://www.businessinsider.co.za/apple-imac-and-ipad-production-will-be-delayed-chip-shortage-2021-4
![20210430-1619784644-001](https://user-images.githubusercontent.com/9846948/116693235-e3c23200-a9bd-11eb-8e6b-aaabf4014048.png)
![20210430-1619784628-001](https://user-images.githubusercontent.com/9846948/116693238-e45ac880-a9bd-11eb-9d69-34e9aa8f799c.png)

https://www.businessinsider.com/biden-first-100-days-how-compare-trump-obama-bush-clinton-2021-4?IR=T#while-trump-was-a-prolific-golfer-during-his-presidency-biden-made-his-first-trip-to-a-golf-course-nearly-three-months-into-his-first-term-9

![20210430-1619784743-001](https://user-images.githubusercontent.com/9846948/116693383-22f08300-a9be-11eb-8e13-2b7712faf840.png)
![20210430-1619784706-001](https://user-images.githubusercontent.com/9846948/116693385-23891980-a9be-11eb-86e5-70f51348ba24.png)

https://www.businessinsider.jp/

![20210430-1619784865-001](https://user-images.githubusercontent.com/9846948/116693562-6814b500-a9be-11eb-948f-d856b371ccd4.png)
![20210430-1619784840-001](https://user-images.githubusercontent.com/9846948/116693567-6945e200-a9be-11eb-8f20-91ffe4a117f8.png)

2021-04-30 12:27 UTC, Gusted commented
Hey! That's weird, we might switch back to remove the `bussinessinsider.*` because on .com and e.g. .nl it works without the fixes.

2021-04-30 12:31 UTC, FadeMind commented
@Gusted  thats why  I specify domains ;)

2021-04-30 12:42 UTC, Gusted approved these changes

2021-04-30 12:42 UTC, merged

2021-04-30 12:45 UTC, FadeMind commented
@Gusted I will pull one more fix for https://www.businessinsider.com.au/ missed in this PR.