Simplified extension badges
darkreader/darkreader pull request #6133
Opened 2021-06-24 23:04 UTC by arche-dev

Changes:
- Made badge text to there respective browser names
- Made alt text more "pretty"

Screenshots:

<details>
<summary>Alt text:</summary>

![image](https://user-images.githubusercontent.com/66189242/123342852-0dbc4e80-d540-11eb-8a60-ff520927973f.png)

![image](https://user-images.githubusercontent.com/66189242/123342929-2dec0d80-d540-11eb-8d22-bc9ca4be4fd9.png)

(Terminal)
![image](https://user-images.githubusercontent.com/66189242/123343059-84594c00-d540-11eb-82ef-a70f37e5133b.png)

</details>

<details>
<summary>Badges</summary>

![image](https://user-images.githubusercontent.com/66189242/123342905-24fb3c00-d540-11eb-8f0e-ba0fad299c64.png)

![image](https://user-images.githubusercontent.com/66189242/123342954-3e9c8380-d540-11eb-90ef-623da010db0d.png)

</details>

2021-06-25 21:16 UTC, Gusted commented
The alt attribute should be descriptive. Let's not cut it down to a single word it shouldn't be looking good, just revert that thing back.

2021-06-26 03:53 UTC, arche-dev commented
Changed :>

2021-06-26 13:14 UTC, Gusted requested changes
remove the `|` in the alt attribute. A screen reader should read the alt without any hiccups.

2021-06-29 14:24 UTC, Gusted approved these changes

2021-06-29 14:24 UTC, merged