Proposal for Issue Templates Overhaul
darkreader/darkreader pull request #6310
Opened 2021-07-19 19:13 UTC by DJ-Katalina

Let's try this again!

I am proposing an overhaul of all 5 current issue templates. I have worked on consistency, clarity, general grammar / spelling / typo corrections, etc.

Thank you. 👍

2021-07-19 19:13 UTC, DJ-Katalina commented
Let's try this again!

I am proposing an overhaul of all 5 current issue templates. I have worked on consistency, clarity, general grammar / spelling / typo corrections, etc.

Thank you. 👍

2021-07-19 21:43 UTC, Gusted requested changes
Reviewed 1 template but most comments can be applied to the other ones.

2021-07-19 21:43 UTC, Gusted commented on .github/ISSUE_TEMPLATE/broken-website.md
> +title: "[Broken Website] Place title here"
We actually had this on before-hand but changed to `Replace with title` as it was thought you would place the title after `place title here` So I would often see `[Broken Website] Place title here *Actually title*`

2021-07-19 21:43 UTC, Gusted commented on .github/ISSUE_TEMPLATE/broken-website.md
> +Thank you for taking the time to create a report about a website issue.
Let's preserve the whitespace.

2021-07-19 21:43 UTC, Gusted commented on .github/ISSUE_TEMPLATE/broken-website.md
> +<!-- Provide steps to reproduce to allow us to troubleshoot this website issue. -->
```suggestion
<!-- Provide steps to reproduce the problem, and allowing us to troubleshoot this website issue. -->
```

2021-07-19 21:43 UTC, Gusted commented on .github/ISSUE_TEMPLATE/broken-website.md
> +<!-- Add screenshots to help explain this website issue. -->
I think we should preserve the `If applicable,` as not every issue would need it and I don't want screenshot when not needed.

2021-07-19 21:43 UTC, Gusted commented on .github/ISSUE_TEMPLATE/broken-website.md
> +Specify the browser name and version as well as the Dark Reader version you are
Whitespace ;)

2021-07-20 00:12 UTC, DJ-Katalina commented
Let me fix a few more issues before review. Sorry.

2021-07-20 00:53 UTC, DJ-Katalina commented
Ok, I believe I am ready for review.

2021-07-20 11:44 UTC, Gusted approved these changes

2021-07-20 11:45 UTC, merged