Add more dark mode sites
darkreader/darkreader pull request #7004
Opened 2021-10-04 04:06 UTC by quick007

2021-10-04 12:32 UTC, Gusted commented on src/config/dark-sites.config
> +dashboard.minefly.org
Not a site? I get a error connection.

2021-10-04 12:32 UTC, Gusted commented on src/config/dark-sites.config
> +vercel.app
Not dark-by-default.

2021-10-04 12:32 UTC, Gusted commented on src/config/dark-sites.config
> +vercel.com
Not dark-by-default.

2021-10-04 16:27 UTC, quick007 commented on src/config/dark-sites.config
> +dashboard.minefly.org
Thanks for catching that, fixed

2021-10-04 17:24 UTC, Gusted approved these changes

2021-10-04 17:24 UTC, Gusted commented on src/config/dark-sites.config
> +dev.minefly.org
This also doesn't seem to add up?
![image](https://user-images.githubusercontent.com/25481501/135896321-37ba94fa-8c90-4b32-9667-144b42ca1741.png)

2021-10-04 17:25 UTC, Gusted requested changes
See comment.

2021-10-05 02:04 UTC, quick007 commented
Works on my machine, even in incognito 
![image](https://user-images.githubusercontent.com/69743171/135948787-ca9ccf3a-23f0-49fa-8860-7e78ff78eb87.png)

2021-10-08 07:45 UTC, rakleed commented
> Works on my machine, even in incognito ![image](https://user-images.githubusercontent.com/69743171/135948787-ca9ccf3a-23f0-49fa-8860-7e78ff78eb87.png)

@quick007 you should enable light theme in your operating system. Then the site will also be displayed in a light theme.

2022-10-04 17:24 UTC, closed without merging