Update color-schemes.drconf || New theme: Gruvbox
darkreader/darkreader pull request #8038
Opened 2022-01-24 05:09 UTC by SparkScratch-P

## A New theme, named Gruvbox has been added. Pls see to it, will be happy to be merged!

2022-01-24 15:22 UTC, Gusted approved these changes
LGTM

2022-01-24 15:23 UTC, Gusted requested changes

2022-01-24 15:23 UTC, Gusted commented on src/config/color-schemes.drconf
> +Gruvbox
This entry isn't in alphabetic order.

2022-01-25 03:24 UTC, SparkScratch-P commented
## I have done the required changes. Please merge this pull.

2022-01-25 09:43 UTC, Gusted approved these changes

2022-01-25 09:44 UTC, merged

2023-06-04 19:24 UTC, dhasial reviewed
I would suggest changing the dark text colour to #c8ba99 which would make it much easier to read text since while still fitting the gruvbox dark aesthetic