Fix of some elements that are not inverted when using the darkmode in Notion website
darkreader/darkreader pull request #8593
Opened 2022-04-04 17:49 UTC by august159

2022-04-04 17:51 UTC, august159 commented
I am confident that the selectors are correct. I am less sure of which dynamic variable to use.

2022-04-05 15:32 UTC, Gusted requested changes

2022-04-05 15:33 UTC, Gusted commented on src/config/dynamic-theme-fixes.config
> +color: var(--darkreader-inline-text) !important;
See: https://github.com/darkreader/darkreader/blob/master/CONTRIBUTING.md#dynamic-variables

2022-04-06 10:38 UTC, august159 reviewed
I have replaced `--darkreader-inline-text` with `--darkreader-neutral-text`

2022-04-06 10:38 UTC, august159 commented on src/config/dynamic-theme-fixes.config
> +color: var(--darkreader-inline-text) !important;
I have replaced `--darkreader-inline-text` with `--darkreader-neutral-text`

2022-04-09 08:53 UTC, Gusted commented on src/config/dynamic-theme-fixes.config
> +}
```suggestion
.notion-page-block,
div[contenteditable="true"],
.notion-page-content div {
    color: var(--darkreader-neutral-text) !important;
}
```

2022-04-09 08:53 UTC, Gusted approved these changes

2022-04-09 08:57 UTC, merged