Provided several fixes for app.betrybe.com
darkreader/darkreader pull request #9116
Opened 2022-06-21 20:14 UTC by gralmeidan

Some sections were inverted, too bright, and/or unreadable

2022-06-21 20:32 UTC, gralmeidan commented
The page is only accessible to students so I grouped all the before/afters [here](https://imgur.com/a/yO8lSus)

2022-06-23 15:54 UTC, gralmeidan commented on src/config/dynamic-theme-fixes.config
> +   background-color: transparent
The original color is white, same as the background 
![a](https://i.imgur.com/s3sVUFy.png) 
INVERT was making it a much darker color 
![a](https://i.imgur.com/bOOZmK2.png) 
so I changed it to transparent 
![a](https://i.imgur.com/tC5MCmu.png)

2022-06-23 16:04 UTC, gralmeidan commented on src/config/dynamic-theme-fixes.config
> +}
Originally it overlayed the entire thing with this very bright color 
![a](https://i.imgur.com/jwJrvuE.png)
I'm honestly not so sure about the `initial` either but Invert didn't work and I'm not that good at raw css so this was the only way I found to make it not suck as much
![a](https://i.imgur.com/lO0DdHe.png)

I didn't know these selectors were auto-generated sorry, I'll be committing a fix

2022-06-24 20:56 UTC, Gusted requested changes
Please add `!important` behind the properties.

2022-06-27 14:22 UTC, Gusted approved these changes

2022-06-27 14:24 UTC, merged