Added few websites to list and fixed Hebrew Language
darkreader/darkreader pull request #9808
Opened 2022-09-12 13:44 UTC by Flaysh

Hey there! I use DarkReader for more than 3 years and pays for the iOS app.
I always wanted to contribute, guess it's time.

- I fixed/improved the Hebrew language

2022-09-13 20:34 UTC, Gusted commented
Hi @Flaysh!

Thank you for your contribution, could please split this PR? So it will show up nicely in the commit graph on the main branch once merged. Please make a separate PR for the added websites and remove them from this PR.

2022-09-14 11:38 UTC, Flaysh commented
Hey, Just did.
New PR on #9819 

Thank u!

2022-09-17 12:45 UTC, Gusted approved these changes
Many thanks!

2022-09-17 12:49 UTC, Gusted requested changes
Please change your PR to match the same amount of lines for each translation key.

2022-09-20 11:09 UTC, Gusted commented on src/_locales/he.config
> +הפעלה אוטומטית
Trailing new line here.

2022-09-20 11:09 UTC, Gusted commented on src/_locales/he.config
> +
```suggestion
```

2022-09-20 11:09 UTC, Gusted commented on src/_locales/he.config
```suggestion


```

2022-09-20 11:27 UTC, Gusted approved these changes

2022-09-20 11:27 UTC, merged